/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
    // Deletes ALL existing entries
    await knex('keywords').del()
    await knex('keywords').insert([
        { word: 'malware' },
        { word: 'security' },
        { word: 'exploit' },
        { word: 'privacy' },
        { word: 'bug' },
        { word: 'hack' },
        { word: 'cybersecurity' },
        { word: 'transparency' },
        { word: 'safety' },
        { word: 'harassment' },
        { word: 'illegal' },
        { word: 'malicious' },
        { word: 'malware' },
        { word: 'spam' },
        { word: 'cybercriminal' },
        { word: 'unauthorized' },
        { word: 'theft' },
        { word: 'disruption' },
        { word: 'vulnerability' },
        { word: 'vulnerabilities' },
        { word: 'attack' },
        { word: 'cyberthreat' },
        { word: 'defense' },
        { word: 'attacks' },
        { word: 'destroy' },
        { word: 'phishing' },
        { word: 'ransomware' },
        { word: 'ddos' },
        { word: 'xss' },
        { word: 'cryptojacking' },
        { word: 'test' },
        { word: 'Fortinet' },
        { word: 'Cisco' },
        { word: 'Crowdstrike' },
        { word: 'IBM' },
        { word: 'McAfee' },
        { word: 'Kaspersky' },
        { word: 'hacker' },
        { word: 'cryptocurrency' },
        { word: 'code' },
        { word: 'online' },
        { word: 'crypto' },
        { word: 'phish' },
        { word: 'botnet' },
        { word: 'misinformation' },
        { word: 'cyberattacker' },
        { word: 'critical' },
        { word: 'credential' },
        { word: 'encryption' },
        { word: 'decrypter' },
        { word: 'sensitive' },
        { word: 'leak' },
        { word: 'email' },
        { word: 'encrypt' },
        { word: 'e2e' },
        { word: 'data' },
        { word: 'library' },
        { word: 'framework' },
        { word: 'git' },
        { word: 'repository' },
        { word: 'account' },
        { word: 'source' },
        { word: 'spy' },
        { word: 'webcam' },
        { word: 'deploy' },
        { word: 'linux' },
        { word: 'vmware' },
        { word: 'novel' },
        { word: 'infrastructure' },
        { word: 'target' },
        { word: 'defi' },
        { word: 'fake' },
        { word: 'platform' },
        { word: 'threat' },
        { word: 'safe' },
        { word: 'ethical' },
        { word: 'iot' },
        { word: 'protection' },
        { word: 'protect' },
        { word: 'recovery' },
        { word: 'breach' },
    ]);
};